spring.application.name=hospital-management

spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_db
spring.datasource.username=postgres
spring.datasource.password=root


spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
sprint.flyway.locations=classpath:/db/migration
spring.flyway.ignore-database-version=true

password=c3086dfc-5feb-4e00-8218-13e07304f0d4